name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # actions/checkout@v4
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Install Rust
        # dtolnay/rust-toolchain@stable
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8

      - name: Cache cargo artifacts
        # Swatinem/rust-cache@v2
        uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae

      - name: Build
        run: cargo build --all-targets --locked

      - name: Test
        run: cargo test --all-targets --locked
